// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartShopPOS.Infrastructure.Persistence;

#nullable disable

namespace SmartShopPOS.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SmartShopPosDbContext))]
    [Migration("20260928204301_CreateBranchAndTerminal")]
    partial class CreateBranchAndTerminal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.AuthenticationSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_authentication_sessions_organization_id");

                    b.HasIndex("SessionId")
                        .IsUnique()
                        .HasDatabaseName("ux_authentication_sessions_session_id");

                    b.HasIndex("TokenHash")
                        .HasDatabaseName("ix_authentication_sessions_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_authentication_sessions_user_id");

                    b.ToTable("authentication_sessions", (string)null);
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_branches_organization_id_id");

                    b.HasIndex("OrganizationId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_branches_organization_id_code");

                    b.ToTable("branches", (string)null);
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_organizations_code");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ux_permissions_key");

                    b.ToTable("permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af01"),
                            Key = "users.view",
                            Name = "View users"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af02"),
                            Key = "users.manage",
                            Name = "Manage users"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af03"),
                            Key = "roles.view",
                            Name = "View roles"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af04"),
                            Key = "roles.manage",
                            Name = "Manage roles"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af05"),
                            Key = "sales.create",
                            Name = "Create sales"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af06"),
                            Key = "reports.view",
                            Name = "View reports"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af07"),
                            Key = "branches.view",
                            Name = "View branches"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af08"),
                            Key = "branches.create",
                            Name = "Create branches"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af09"),
                            Key = "branches.update",
                            Name = "Update branches"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af0a"),
                            Key = "branches.deactivate",
                            Name = "Deactivate branches"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af0b"),
                            Key = "terminals.view",
                            Name = "View terminals"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af0c"),
                            Key = "terminals.create",
                            Name = "Create terminals"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af0d"),
                            Key = "terminals.update",
                            Name = "Update terminals"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af0e"),
                            Key = "terminals.deactivate",
                            Name = "Deactivate terminals"
                        });
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_roles_organization_id_id");

                    b.HasIndex("OrganizationId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_roles_organization_normalized_name");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_role_permissions");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.Terminal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_terminals_branch_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_terminals_organization_id");

                    b.HasIndex("BranchId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_terminals_branch_id_code");

                    b.HasIndex("OrganizationId", "BranchId");

                    b.ToTable("terminals", (string)null);
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_users_organization_id_id");

                    b.HasIndex("OrganizationId", "NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_users_organization_normalized_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_user_roles_organization_id");

                    b.HasIndex("OrganizationId", "RoleId");

                    b.HasIndex("OrganizationId", "UserId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.AuthenticationSession", b =>
                {
                    b.HasOne("SmartShopPOS.Domain.Identity.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartShopPOS.Domain.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.Branch", b =>
                {
                    b.HasOne("SmartShopPOS.Domain.Identity.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.Role", b =>
                {
                    b.HasOne("SmartShopPOS.Domain.Identity.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.RolePermission", b =>
                {
                    b.HasOne("SmartShopPOS.Domain.Identity.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartShopPOS.Domain.Identity.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.Terminal", b =>
                {
                    b.HasOne("SmartShopPOS.Domain.Identity.Branch", "Branch")
                        .WithMany("Terminals")
                        .HasForeignKey("OrganizationId", "BranchId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.User", b =>
                {
                    b.HasOne("SmartShopPOS.Domain.Identity.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.UserRole", b =>
                {
                    b.HasOne("SmartShopPOS.Domain.Identity.Role", "Role")
                        .WithMany()
                        .HasForeignKey("OrganizationId", "RoleId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartShopPOS.Domain.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("OrganizationId", "UserId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.Branch", b =>
                {
                    b.Navigation("Terminals");
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.Role", b =>
                {
                    b.Navigation("RolePermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
