// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartShopPOS.Infrastructure.Persistence;

#nullable disable

namespace SmartShopPOS.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SmartShopPosDbContext))]
    [Migration("20261001080107_CreateSupplierInvoiceFoundation")]
    partial class CreateSupplierInvoiceFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.AuthenticationSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SelectedBranchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_authentication_sessions_organization_id");

                    b.HasIndex("SelectedBranchId")
                        .HasDatabaseName("ix_authentication_sessions_selected_branch_id");

                    b.HasIndex("SessionId")
                        .IsUnique()
                        .HasDatabaseName("ux_authentication_sessions_session_id");

                    b.HasIndex("TokenHash")
                        .HasDatabaseName("ix_authentication_sessions_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_authentication_sessions_user_id");

                    b.HasIndex("OrganizationId", "SelectedBranchId");

                    b.ToTable("authentication_sessions", (string)null);
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_branches_organization_id_id");

                    b.HasIndex("OrganizationId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_branches_organization_id_code");

                    b.ToTable("branches", (string)null);
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_brands_organization_id_id");

                    b.HasIndex("OrganizationId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_brands_organization_normalized_name");

                    b.ToTable("brands", (string)null);
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_categories_organization_id_id");

                    b.HasIndex("OrganizationId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_categories_organization_normalized_name");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.GoodsReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_goods_receipts_organization_id_id");

                    b.HasAlternateKey("OrganizationId", "PurchaseOrderId", "Id")
                        .HasName("ak_goods_receipts_organization_order_id");

                    b.HasIndex("OrganizationId", "CreatedByUserId");

                    b.HasIndex("OrganizationId", "PurchaseOrderId")
                        .HasDatabaseName("ix_goods_receipts_organization_order");

                    b.HasIndex("OrganizationId", "ReceiptNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_goods_receipts_organization_number");

                    b.HasIndex("OrganizationId", "ReceivedAt")
                        .HasDatabaseName("ix_goods_receipts_organization_received_at");

                    b.ToTable("goods_receipts", (string)null);
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.GoodsReceiptIdempotency", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("GoodsReceiptId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("OrganizationId", "Key");

                    b.HasIndex("GoodsReceiptId")
                        .IsUnique();

                    b.ToTable("goods_receipt_idempotency", (string)null);
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.GoodsReceiptLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GoodsReceiptId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PurchaseOrderLineId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QuantityReceived")
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "PurchaseOrderLineId")
                        .HasDatabaseName("ix_goods_receipt_lines_organization_order_line");

                    b.HasIndex("OrganizationId", "GoodsReceiptId", "PurchaseOrderLineId")
                        .IsUnique()
                        .HasDatabaseName("ux_goods_receipt_lines_receipt_order_line");

                    b.HasIndex("OrganizationId", "PurchaseOrderId", "GoodsReceiptId");

                    b.HasIndex("OrganizationId", "PurchaseOrderId", "PurchaseOrderLineId");

                    b.ToTable("goods_receipt_lines", null, t =>
                        {
                            t.HasCheckConstraint("ck_goods_receipt_lines_quantity_positive", "\"QuantityReceived\" > 0");
                        });
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.GoodsReceiptNumberSequence", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<long>("LastNumber")
                        .HasColumnType("bigint");

                    b.HasKey("OrganizationId");

                    b.ToTable("goods_receipt_number_sequences", null, t =>
                        {
                            t.HasCheckConstraint("ck_goods_receipt_number_sequences_last_number_positive", "\"LastNumber\" > 0");
                        });
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.InventoryBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QuantityOnHand")
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_inventory_balances_organization_id_id");

                    b.HasIndex("OrganizationId", "BranchId")
                        .HasDatabaseName("ix_inventory_balances_organization_branch");

                    b.HasIndex("OrganizationId", "ProductId")
                        .HasDatabaseName("ix_inventory_balances_organization_product");

                    b.HasIndex("OrganizationId", "BranchId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("ux_inventory_balances_organization_branch_product");

                    b.ToTable("inventory_balances", null, t =>
                        {
                            t.HasCheckConstraint("ck_inventory_balances_quantity_non_negative", "\"QuantityOnHand\" >= 0");
                        });
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_organizations_code");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ux_permissions_key");

                    b.ToTable("permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af01"),
                            Key = "users.view",
                            Name = "View users"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af02"),
                            Key = "users.manage",
                            Name = "Manage users"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af03"),
                            Key = "roles.view",
                            Name = "View roles"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af04"),
                            Key = "roles.manage",
                            Name = "Manage roles"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af05"),
                            Key = "sales.create",
                            Name = "Create sales"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af06"),
                            Key = "reports.view",
                            Name = "View reports"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af07"),
                            Key = "branches.view",
                            Name = "View branches"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af08"),
                            Key = "branches.create",
                            Name = "Create branches"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af09"),
                            Key = "branches.update",
                            Name = "Update branches"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af0a"),
                            Key = "branches.deactivate",
                            Name = "Deactivate branches"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af0b"),
                            Key = "terminals.view",
                            Name = "View terminals"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af0c"),
                            Key = "terminals.create",
                            Name = "Create terminals"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af0d"),
                            Key = "terminals.update",
                            Name = "Update terminals"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af0e"),
                            Key = "terminals.deactivate",
                            Name = "Deactivate terminals"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af0f"),
                            Key = "user_branch_assignments.view",
                            Name = "View user branch assignments"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af10"),
                            Key = "user_branch_assignments.create",
                            Name = "Assign users to branches"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af11"),
                            Key = "user_branch_assignments.deactivate",
                            Name = "Deactivate user branch assignments"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af12"),
                            Key = "branch_context.select",
                            Name = "Select operational branch context"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af13"),
                            Key = "products.view",
                            Name = "View products"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af14"),
                            Key = "products.create",
                            Name = "Create products"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af15"),
                            Key = "products.update",
                            Name = "Update products"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af16"),
                            Key = "products.deactivate",
                            Name = "Deactivate products"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af17"),
                            Key = "categories.view",
                            Name = "View categories"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af18"),
                            Key = "categories.create",
                            Name = "Create categories"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af19"),
                            Key = "categories.update",
                            Name = "Update categories"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af1a"),
                            Key = "categories.deactivate",
                            Name = "Deactivate categories"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af1b"),
                            Key = "brands.view",
                            Name = "View brands"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af1c"),
                            Key = "brands.create",
                            Name = "Create brands"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af1d"),
                            Key = "brands.update",
                            Name = "Update brands"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af1e"),
                            Key = "brands.deactivate",
                            Name = "Deactivate brands"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af1f"),
                            Key = "units.view",
                            Name = "View units"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af20"),
                            Key = "units.create",
                            Name = "Create units"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af21"),
                            Key = "units.update",
                            Name = "Update units"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af22"),
                            Key = "units.deactivate",
                            Name = "Deactivate units"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af23"),
                            Key = "tax_categories.view",
                            Name = "View tax categories"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af24"),
                            Key = "tax_categories.create",
                            Name = "Create tax categories"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af25"),
                            Key = "tax_categories.update",
                            Name = "Update tax categories"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af26"),
                            Key = "tax_categories.deactivate",
                            Name = "Deactivate tax categories"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af27"),
                            Key = "products.prices.view",
                            Name = "View product prices"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af28"),
                            Key = "products.prices.create",
                            Name = "Create product prices"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af29"),
                            Key = "inventory.view",
                            Name = "View inventory balances"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af2a"),
                            Key = "inventory.opening_balance",
                            Name = "Create inventory opening balances"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af2b"),
                            Key = "inventory.adjust",
                            Name = "Adjust inventory"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af2c"),
                            Key = "inventory.movements.view",
                            Name = "View stock movements"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af2d"),
                            Key = "suppliers.view",
                            Name = "View suppliers"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af2e"),
                            Key = "suppliers.create",
                            Name = "Create suppliers"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af2f"),
                            Key = "suppliers.update",
                            Name = "Update suppliers"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af30"),
                            Key = "suppliers.deactivate",
                            Name = "Deactivate suppliers"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af31"),
                            Key = "purchase_orders.view",
                            Name = "View purchase orders"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af32"),
                            Key = "purchase_orders.create",
                            Name = "Create purchase orders"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af33"),
                            Key = "purchase_orders.update",
                            Name = "Update draft purchase orders"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af34"),
                            Key = "purchase_orders.submit",
                            Name = "Submit purchase orders"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af35"),
                            Key = "purchase_orders.cancel",
                            Name = "Cancel purchase orders"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af36"),
                            Key = "purchase_orders.lines.view",
                            Name = "View purchase order lines"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af37"),
                            Key = "purchase_orders.lines.create",
                            Name = "Add purchase order lines"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af38"),
                            Key = "purchase_orders.lines.update",
                            Name = "Update purchase order lines"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af39"),
                            Key = "purchase_orders.lines.delete",
                            Name = "Delete purchase order lines"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af3a"),
                            Key = "goods_receipts.view",
                            Name = "View goods receipts"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af3b"),
                            Key = "goods_receipts.create",
                            Name = "Create goods receipts"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af3c"),
                            Key = "supplier_invoices.view",
                            Name = "View supplier invoices"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af3d"),
                            Key = "supplier_invoices.create",
                            Name = "Create supplier invoices"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af3e"),
                            Key = "supplier_invoices.update",
                            Name = "Update draft supplier invoices"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af3f"),
                            Key = "supplier_invoices.post",
                            Name = "Post supplier invoices"
                        },
                        new
                        {
                            Id = new Guid("dd733879-15dd-4bdd-9a1b-068cc4c5af40"),
                            Key = "supplier_invoices.cancel",
                            Name = "Cancel draft supplier invoices"
                        });
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Barcode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("BrandId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("TaxCategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UnitOfMeasureId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_products_organization_id_id");

                    b.HasIndex("OrganizationId", "Barcode")
                        .IsUnique()
                        .HasDatabaseName("ux_products_organization_barcode")
                        .HasFilter("\"Barcode\" IS NOT NULL");

                    b.HasIndex("OrganizationId", "BrandId")
                        .HasDatabaseName("ix_products_organization_brand");

                    b.HasIndex("OrganizationId", "CategoryId")
                        .HasDatabaseName("ix_products_organization_category");

                    b.HasIndex("OrganizationId", "IsActive")
                        .HasDatabaseName("ix_products_organization_active");

                    b.HasIndex("OrganizationId", "Sku")
                        .IsUnique()
                        .HasDatabaseName("ux_products_organization_sku");

                    b.HasIndex("OrganizationId", "TaxCategoryId");

                    b.HasIndex("OrganizationId", "UnitOfMeasureId");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.ProductPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("SellingPrice")
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("ux_product_prices_organization_product_active")
                        .HasFilter("\"EffectiveTo\" IS NULL");

                    b.HasIndex("OrganizationId", "ProductId", "EffectiveFrom")
                        .HasDatabaseName("ix_product_prices_organization_product_effective_from");

                    b.HasIndex("OrganizationId", "ProductId", "EffectiveTo")
                        .HasDatabaseName("ix_product_prices_organization_product_effective_to");

                    b.ToTable("product_prices", (string)null);
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.PurchaseOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ExpectedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_purchase_orders_organization_id_id");

                    b.HasAlternateKey("OrganizationId", "SupplierId", "Id")
                        .HasName("ak_purchase_orders_organization_supplier_id");

                    b.HasIndex("OrganizationId", "BranchId")
                        .HasDatabaseName("ix_purchase_orders_organization_branch");

                    b.HasIndex("OrganizationId", "CreatedByUserId");

                    b.HasIndex("OrganizationId", "OrderDate")
                        .HasDatabaseName("ix_purchase_orders_organization_order_date");

                    b.HasIndex("OrganizationId", "OrderNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_purchase_orders_organization_order_number");

                    b.HasIndex("OrganizationId", "Status")
                        .HasDatabaseName("ix_purchase_orders_organization_status");

                    b.HasIndex("OrganizationId", "SupplierId")
                        .HasDatabaseName("ix_purchase_orders_organization_supplier");

                    b.HasIndex("OrganizationId", "UpdatedByUserId");

                    b.ToTable("purchase_orders", null, t =>
                        {
                            t.HasCheckConstraint("ck_purchase_orders_status_valid", "\"Status\" BETWEEN 1 AND 3");
                        });
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.PurchaseOrderLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "PurchaseOrderId", "Id")
                        .HasName("ak_purchase_order_lines_organization_order_id");

                    b.HasIndex("OrganizationId", "ProductId")
                        .HasDatabaseName("ix_purchase_order_lines_organization_product");

                    b.HasIndex("OrganizationId", "PurchaseOrderId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("ux_purchase_order_lines_organization_order_product");

                    b.ToTable("purchase_order_lines", null, t =>
                        {
                            t.HasCheckConstraint("ck_purchase_order_lines_quantity_positive", "\"Quantity\" > 0");

                            t.HasCheckConstraint("ck_purchase_order_lines_unit_cost_non_negative", "\"UnitCost\" >= 0");
                        });
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.PurchaseOrderNumberSequence", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<long>("LastNumber")
                        .HasColumnType("bigint");

                    b.HasKey("OrganizationId");

                    b.ToTable("purchase_order_number_sequences", null, t =>
                        {
                            t.HasCheckConstraint("ck_purchase_order_number_sequences_last_number_positive", "\"LastNumber\" > 0");
                        });
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_roles_organization_id_id");

                    b.HasIndex("OrganizationId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_roles_organization_normalized_name");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_role_permissions");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.StockMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("MovementType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_stock_movements_organization_id_id");

                    b.HasIndex("OrganizationId", "BranchId", "OccurredAt")
                        .HasDatabaseName("ix_stock_movements_organization_branch_occurred");

                    b.HasIndex("OrganizationId", "ProductId", "OccurredAt")
                        .HasDatabaseName("ix_stock_movements_organization_product_occurred");

                    b.HasIndex("OrganizationId", "BranchId", "ProductId", "OccurredAt")
                        .HasDatabaseName("ix_stock_movements_organization_branch_product_occurred");

                    b.ToTable("stock_movements", null, t =>
                        {
                            t.HasCheckConstraint("ck_stock_movements_quantity_positive", "\"Quantity\" > 0");

                            t.HasCheckConstraint("ck_stock_movements_type_valid", "\"MovementType\" BETWEEN 1 AND 6");
                        });
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("BusinessRegistrationNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Phone")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TaxIdentifier")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_suppliers_organization_id_id");

                    b.HasIndex("OrganizationId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_suppliers_organization_code");

                    b.HasIndex("OrganizationId", "IsActive")
                        .HasDatabaseName("ix_suppliers_organization_active");

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.SupplierInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<decimal>("GrossAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("InternalNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateOnly>("InvoiceDate")
                        .HasColumnType("date");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("NormalizedInvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("OtherTaxAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset?>("PostedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PostedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PurchaseOrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("SupplierDocumentGrossAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("SupplierDocumentNetAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("SupplierDocumentVatAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_supplier_invoices_organization_id_id");

                    b.HasIndex("OrganizationId", "CreatedByUserId");

                    b.HasIndex("OrganizationId", "InternalNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_supplier_invoices_organization_internal_number");

                    b.HasIndex("OrganizationId", "PostedByUserId");

                    b.HasIndex("OrganizationId", "PurchaseOrderId")
                        .HasDatabaseName("ix_supplier_invoices_organization_order");

                    b.HasIndex("OrganizationId", "Status", "InvoiceDate")
                        .HasDatabaseName("ix_supplier_invoices_organization_status_date");

                    b.HasIndex("OrganizationId", "SupplierId", "NormalizedInvoiceNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_supplier_invoices_organization_supplier_invoice_number");

                    b.HasIndex("OrganizationId", "SupplierId", "PurchaseOrderId");

                    b.ToTable("supplier_invoices", null, t =>
                        {
                            t.HasCheckConstraint("ck_supplier_invoices_status_valid", "\"Status\" BETWEEN 1 AND 3");
                        });
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.SupplierInvoiceLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PurchaseOrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PurchaseOrderLineId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("SupplierInvoiceId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("TaxCategoryId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "SupplierInvoiceId")
                        .HasDatabaseName("ix_supplier_invoice_lines_organization_invoice");

                    b.HasIndex("OrganizationId", "TaxCategoryId");

                    b.HasIndex("OrganizationId", "PurchaseOrderId", "PurchaseOrderLineId")
                        .HasDatabaseName("ix_supplier_invoice_lines_organization_order_line");

                    b.ToTable("supplier_invoice_lines", null, t =>
                        {
                            t.HasCheckConstraint("ck_supplier_invoice_lines_po_reference_pair", "(\"PurchaseOrderId\" IS NULL) = (\"PurchaseOrderLineId\" IS NULL)");

                            t.HasCheckConstraint("ck_supplier_invoice_lines_quantity_positive", "\"Quantity\" > 0");

                            t.HasCheckConstraint("ck_supplier_invoice_lines_tax_amount_nonnegative", "\"TaxAmount\" >= 0");

                            t.HasCheckConstraint("ck_supplier_invoice_lines_unit_price_nonnegative", "\"UnitPrice\" >= 0");
                        });
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.SupplierInvoiceNumberSequence", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<long>("LastNumber")
                        .HasColumnType("bigint");

                    b.HasKey("OrganizationId");

                    b.ToTable("supplier_invoice_number_sequences", null, t =>
                        {
                            t.HasCheckConstraint("ck_supplier_invoice_number_sequences_last_number_positive", "\"LastNumber\" > 0");
                        });
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.TaxCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Rate")
                        .HasPrecision(6, 3)
                        .HasColumnType("numeric(6,3)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_tax_categories_organization_id_id");

                    b.HasIndex("OrganizationId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_tax_categories_organization_code");

                    b.HasIndex("OrganizationId", "IsActive")
                        .HasDatabaseName("ix_tax_categories_organization_active");

                    b.ToTable("tax_categories", null, t =>
                        {
                            t.HasCheckConstraint("ck_tax_categories_rate_percentage", "\"Rate\" >= 0 AND \"Rate\" <= 100");
                        });
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.Terminal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_terminals_branch_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_terminals_organization_id");

                    b.HasIndex("BranchId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_terminals_branch_id_code");

                    b.HasIndex("OrganizationId", "BranchId");

                    b.ToTable("terminals", (string)null);
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.UnitOfMeasure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Symbol")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_units_of_measure_organization_id_id");

                    b.HasIndex("OrganizationId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_units_of_measure_organization_code");

                    b.HasIndex("OrganizationId", "IsActive")
                        .HasDatabaseName("ix_units_of_measure_organization_active");

                    b.ToTable("units_of_measure", (string)null);
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_users_organization_id_id");

                    b.HasIndex("OrganizationId", "NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_users_organization_normalized_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.UserBranch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "BranchId")
                        .HasDatabaseName("ix_user_branches_organization_branch");

                    b.HasIndex("OrganizationId", "UserId")
                        .HasDatabaseName("ix_user_branches_organization_user");

                    b.HasIndex("OrganizationId", "UserId", "BranchId")
                        .IsUnique()
                        .HasDatabaseName("ux_user_branches_active_assignment")
                        .HasFilter("\"DeactivatedAt\" IS NULL");

                    b.ToTable("user_branches", (string)null);
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_user_roles_organization_id");

                    b.HasIndex("OrganizationId", "RoleId");

                    b.HasIndex("OrganizationId", "UserId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.AuthenticationSession", b =>
                {
                    b.HasOne("SmartShopPOS.Domain.Identity.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartShopPOS.Domain.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartShopPOS.Domain.Identity.Branch", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "SelectedBranchId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.Branch", b =>
                {
                    b.HasOne("SmartShopPOS.Domain.Identity.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.Brand", b =>
                {
                    b.HasOne("SmartShopPOS.Domain.Identity.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.Category", b =>
                {
                    b.HasOne("SmartShopPOS.Domain.Identity.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.GoodsReceipt", b =>
                {
                    b.HasOne("SmartShopPOS.Domain.Identity.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartShopPOS.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "CreatedByUserId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartShopPOS.Domain.Identity.PurchaseOrder", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "PurchaseOrderId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.GoodsReceiptIdempotency", b =>
                {
                    b.HasOne("SmartShopPOS.Domain.Identity.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.GoodsReceiptLine", b =>
                {
                    b.HasOne("SmartShopPOS.Domain.Identity.GoodsReceipt", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "PurchaseOrderId", "GoodsReceiptId")
                        .HasPrincipalKey("OrganizationId", "PurchaseOrderId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartShopPOS.Domain.Identity.PurchaseOrderLine", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "PurchaseOrderId", "PurchaseOrderLineId")
                        .HasPrincipalKey("OrganizationId", "PurchaseOrderId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.GoodsReceiptNumberSequence", b =>
                {
                    b.HasOne("SmartShopPOS.Domain.Identity.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.InventoryBalance", b =>
                {
                    b.HasOne("SmartShopPOS.Domain.Identity.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartShopPOS.Domain.Identity.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("OrganizationId", "BranchId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartShopPOS.Domain.Identity.Product", "Product")
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ProductId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Organization");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.Product", b =>
                {
                    b.HasOne("SmartShopPOS.Domain.Identity.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartShopPOS.Domain.Identity.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("OrganizationId", "BrandId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartShopPOS.Domain.Identity.Category", "Category")
                        .WithMany()
                        .HasForeignKey("OrganizationId", "CategoryId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartShopPOS.Domain.Identity.TaxCategory", "TaxCategory")
                        .WithMany()
                        .HasForeignKey("OrganizationId", "TaxCategoryId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartShopPOS.Domain.Identity.UnitOfMeasure", "UnitOfMeasure")
                        .WithMany()
                        .HasForeignKey("OrganizationId", "UnitOfMeasureId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");

                    b.Navigation("Organization");

                    b.Navigation("TaxCategory");

                    b.Navigation("UnitOfMeasure");
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.ProductPrice", b =>
                {
                    b.HasOne("SmartShopPOS.Domain.Identity.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartShopPOS.Domain.Identity.Product", "Product")
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ProductId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.PurchaseOrder", b =>
                {
                    b.HasOne("SmartShopPOS.Domain.Identity.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartShopPOS.Domain.Identity.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("OrganizationId", "BranchId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartShopPOS.Domain.Identity.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("OrganizationId", "CreatedByUserId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartShopPOS.Domain.Identity.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("OrganizationId", "SupplierId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartShopPOS.Domain.Identity.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("OrganizationId", "UpdatedByUserId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Branch");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Organization");

                    b.Navigation("Supplier");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.PurchaseOrderLine", b =>
                {
                    b.HasOne("SmartShopPOS.Domain.Identity.Product", "Product")
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ProductId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartShopPOS.Domain.Identity.PurchaseOrder", "PurchaseOrder")
                        .WithMany()
                        .HasForeignKey("OrganizationId", "PurchaseOrderId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.PurchaseOrderNumberSequence", b =>
                {
                    b.HasOne("SmartShopPOS.Domain.Identity.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.Role", b =>
                {
                    b.HasOne("SmartShopPOS.Domain.Identity.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.RolePermission", b =>
                {
                    b.HasOne("SmartShopPOS.Domain.Identity.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartShopPOS.Domain.Identity.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.StockMovement", b =>
                {
                    b.HasOne("SmartShopPOS.Domain.Identity.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartShopPOS.Domain.Identity.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("OrganizationId", "BranchId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartShopPOS.Domain.Identity.Product", "Product")
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ProductId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Organization");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.Supplier", b =>
                {
                    b.HasOne("SmartShopPOS.Domain.Identity.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.SupplierInvoice", b =>
                {
                    b.HasOne("SmartShopPOS.Domain.Identity.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartShopPOS.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "CreatedByUserId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartShopPOS.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "PostedByUserId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartShopPOS.Domain.Identity.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("OrganizationId", "SupplierId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartShopPOS.Domain.Identity.PurchaseOrder", "PurchaseOrder")
                        .WithMany()
                        .HasForeignKey("OrganizationId", "SupplierId", "PurchaseOrderId")
                        .HasPrincipalKey("OrganizationId", "SupplierId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PurchaseOrder");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.SupplierInvoiceLine", b =>
                {
                    b.HasOne("SmartShopPOS.Domain.Identity.SupplierInvoice", null)
                        .WithMany("Lines")
                        .HasForeignKey("OrganizationId", "SupplierInvoiceId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartShopPOS.Domain.Identity.TaxCategory", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "TaxCategoryId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartShopPOS.Domain.Identity.PurchaseOrderLine", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "PurchaseOrderId", "PurchaseOrderLineId")
                        .HasPrincipalKey("OrganizationId", "PurchaseOrderId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.SupplierInvoiceNumberSequence", b =>
                {
                    b.HasOne("SmartShopPOS.Domain.Identity.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.TaxCategory", b =>
                {
                    b.HasOne("SmartShopPOS.Domain.Identity.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.Terminal", b =>
                {
                    b.HasOne("SmartShopPOS.Domain.Identity.Branch", "Branch")
                        .WithMany("Terminals")
                        .HasForeignKey("OrganizationId", "BranchId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.UnitOfMeasure", b =>
                {
                    b.HasOne("SmartShopPOS.Domain.Identity.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.User", b =>
                {
                    b.HasOne("SmartShopPOS.Domain.Identity.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.UserBranch", b =>
                {
                    b.HasOne("SmartShopPOS.Domain.Identity.Branch", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "BranchId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartShopPOS.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "UserId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.UserRole", b =>
                {
                    b.HasOne("SmartShopPOS.Domain.Identity.Role", "Role")
                        .WithMany()
                        .HasForeignKey("OrganizationId", "RoleId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartShopPOS.Domain.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("OrganizationId", "UserId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.Branch", b =>
                {
                    b.Navigation("Terminals");
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.Role", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("SmartShopPOS.Domain.Identity.SupplierInvoice", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
