<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartShopPOS.Contracts\SmartShopPOS.Contracts.csproj" />
    <ProjectReference Include="..\SmartShopPOS.Domain\SmartShopPOS.Domain.csproj" />
  </ItemGroup>

</Project>
